spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/investment_platform
spring.datasource.username=Eshita
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.address=0.0.0.0
server.port=8080
ml.service.retrain.url=http://localhost:5001/retrain
ml.service.url=http://localhost:5001
ml.service.timeout=30000
spring.jpa.properties.hibernate.generate_statistics=true
spring.mvc.async.request-timeout=PT120S
